---

# Homebrew
- name: Install development npm modules
  shell: npm install -g {{ item.name }} creates={{ node_dev_brew_path }}/{{ item.bin }}
  with_items:
    - { name: 'bower', bin: 'bower' }
    - { name: 'express-generator', bin: 'express' }
    - { name: 'grunt-cli', bin: 'grunt' }
    - { name: 'gulp-cli', bin: 'gulp' }
    - { name: 'nodemon', bin: 'nodemon' }
  environment:
    PATH: "{{ host_package_manager_paths }}{{ ansible_env.PATH }}"
  when: ansible_pkg_mgr == 'homebrew'
